name: crawl

on:
  schedule:
    - cron: '38 * * * *'

env:
  CRAWLER_VERSION: "0.4.5"

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT}}

      - name: INSTALL - python@3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Kernel Crawler
        run: pip install -U git+https://github.com/falcosecurity/kernel-crawler.git@$CRAWLER_VERSION

      - name: Crawl
        run: python -m kernel_crawler.main crawl --distro AmazonLinux2 --out_fmt driverkit > kernels/amazonlinux2.json

      - name: Commit and Push
        run: ./.github/commit-and-push.sh
        env:
          NAME: ${{ secrets.NAME }}
          EMAIL: ${{ secrets.EMAIL }}
